package com.example.animalcare.models;

import java.io.Serializable;

public class Animal implements Serializable {
    // data introduced by user
    private double age;
    private String gender;
    private String species;
    private String color;
    private String description;
    private boolean disease;
    private String image;
    private String arrivingDate;
    private String breed;
    // 3 sizes: 1 - small, 2 - medium, 3 - big
    private int size;
    // 3 types of personality: 1 - inactive, 2 - nearly-active, 3 - active
    private int personalityType;

    // autogenerated data
    private String animalID;
    private boolean wasAdopted;
    // 3 levels
    private int attentionLevelRequired;
    private int caringLevelRequired;

    public Animal() {
    }

    public Animal(String arrivingDate, double age, String gender, String species, String color,
                  String description, boolean disease, int personalityType, int size,
                  String animalID, String image) {
        this.arrivingDate = arrivingDate;
        this.age = age;
        this.gender = gender;
        this.species = species;
        this.color = color;
        this.description = description;
        this.disease = disease;
        this.personalityType = personalityType;
        this.size = size;
        this.animalID = animalID;
        this.image = image;
        this.wasAdopted = false;

        calculateAttentionLevelRequired();
        calculateCaringLevelRequired();
    }
    public void calculateAttentionLevelRequired() {
        int level = 0;

        if (this.age < 1) {
            level += 20;
        } else if (this.age < 3) {
            level += 10;
        } else if (this.age < 5) {
            level += 5;
        }

        if (this.species.equals(DOG)) {
            level += 5;
        }

        if (this.personalityType == 3) {
            level += 20;
        } else if (this.personalityType == 2) {
            level += 10;
        }

        if (level <= 15) {
            this.attentionLevelRequired = 1;
        } else if (level <= 30) {
            this.attentionLevelRequired = 2;
        } else {
            this.attentionLevelRequired = 3;
        }
    }

    private void calculateCaringLevelRequired() {
        int level = 0;

        if (this.age < 1) {
            level += 20;
        }

        if (this.gender.equals(FEMALE)) {
            level += 10;
        }

        if (this.getDisease()) {
            level += 15;
        }

        if (this.size == 3) {
            level += 10;
        }

        if (level <= 20) {
            this.caringLevelRequired = 1;
        } else if (level <= 35) {
            this.caringLevelRequired = 2;
        } else {
            this.caringLevelRequired = 3;
        }
    }

    public double getAge() {
        return age;
    }

    public void setAge(double age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean getDisease() {
        return disease;
    }

    public void setDisease(boolean disease) {
        this.disease = disease;
    }

    public int getPersonalityType() {
        return personalityType;
    }

    public void setPersonalityType(int personalityType) {
        this.personalityType = personalityType;
    }

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    public String getAnimalID() {
        return animalID;
    }

    public void setAnimalID(String animalID) {
        this.animalID = animalID;
    }

    public int getAttentionLevelRequired() {
        return attentionLevelRequired;
    }

    public void setAttentionLevelRequired(int attentionLevelRequired) {
        this.attentionLevelRequired = attentionLevelRequired;
    }

    public int getCaringLevelRequired() {
        return caringLevelRequired;
    }

    public void setCaringLevelRequired(int caringLevelRequired) {
        this.caringLevelRequired = caringLevelRequired;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getBreed() {
        return breed;
    }

    public void setBreed(String breed) {
        this.breed = breed;
    }

    public String getArrivingDate() {
        return arrivingDate;
    }

    public void setArrivingDate(String arrivingDate) {
        this.arrivingDate = arrivingDate;
    }

    public boolean getWasAdopted() {
        return wasAdopted;
    }

    public void setWasAdopted(boolean wasAdopted) {
        this.wasAdopted = wasAdopted;
    }

    public static final String FEMALE  = "FEMALE";
    public static final String MALE  = "MALE";
    public static final String DOG  = "DOG";
    public static final String CAT  = "CAT";

}
